version: 2

models:
  - name: stg_ae_local_bike__brands
    description: This model maps the brand name to its unique identifier
    columns:
      - name: brand_id
        description: Primary key, unique identifier for a brand 
        tests:
          - unique
          - not_null
      - name: brand_name
        description: This is the brand name
  
  - name: stg_ae_local_bike__categories
    description: This model maps the product categories to its unique identifier
    columns:
      - name: category_id
        description: Primary key, unique identifier for a product category
        tests:
          - unique
          - not_null
      - name: category_name
        description: This is the name of the product category
  
  - name: stg_ae_local_bike__customers
    description: This model gives information about a customer personal information with his full name, contacts and address
    columns:
      - name: customer_id
        description: Primary key, unique identifier for a customer
        tests:
          - unique
          - not_null
  
  - name: stg_ae_local_bike__order_items
    description: This model lists the products purchased in an order, the quantity of each item and their price
    columns:
      - name: order_item_id
        description: Primary key, unique identifier for the order item, generated by combining the order_id and the item_id
        tests:
          - unique
          - not_null
      - name: order_id
        description: Foreign key referencing the 'stg_ae_local_bike__orders.order_id' column
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_ae_local_bike__orders
              to: ref('stg_ae_local_bike__orders')
              field: order_id
      - name: item_id
        description: This is an id that numbers each product that is put in an order
        tests:
          - not_null
      - name: product_id
        description: Foreign key referencing the 'stg_ae_local_bike__products.product_id' column
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_ae_local_bike__products
              to: ref('stg_ae_local_bike__products')
              field: product_id

  - name: stg_ae_local_bike__orders
    description: This model gives information about who placed an order, from which store with which staff member, its status and its shipment details
    columns:
      - name: order_id
        description: Primary key, unique identifier for the order
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key referencing the 'stg_ae_local_bike__customers.customer_id' column
        tests:
          - relationships: 
              name: customer_id_foreign_key_in_stg_ae_local_bike__customers
              to: ref('stg_ae_local_bike__customers')
              field: customer_id
      - name: order_status
        description: This is the step of the order
        tests:
          - accepted_values:
              values: [1,2,3,4]
              quote: false
      - name: order_date
        description: Date of when the order was placed
        tests:
          - not_null
      - name: required_date
        description: Delivery date required by the customer
        tests:
          - not_null
      - name: shipped_date
        description: The date the order was sent
      - name: store_id
        description: Foreign key referencing the 'stg_ae_local_bike__stores.store_id'
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_ae_local_bike__stores
              to: ref('stg_ae_local_bike__stores')
              field: store_id
      - name: staff_id
        description: Foreign key referencing the 'stg_ae_local_bike__staffs.staff_id
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_ae_local_bike__staffs
              to: ref('stg_ae_local_bike__staffs')
              field: staff_id

  - name: stg_ae_local_bike__products
    description: This model gives information about the products
    columns: 
      - name: product_id
        description: Primary key, unique identifier for a product
        tests:
          - unique
          - not_null
      - name: product_name
        description: This is the name of the product
        tests:
          - not_null
      - name: brand_id
        description: Foreign key referencing the 'stg_ae_local_bike__brands.brand_id' column
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_ae_local_bike__brands
              to: ref('stg_ae_local_bike__brands')
              field: brand_id
      - name: category_id
        description: Foreign key referencing the 'stg_ae_local_bike__categories.category_id' column
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_ae_local_bike__categories
              to: ref('stg_ae_local_bike__categories')
              field: category_id

  - name: stg_ae_local_bike__staffs
    description: This model lists staff members and their details
    columns:
      - name: staff_id
        description: Primary key, unique identifier of a staff member
        tests:
          - unique
          - not_null
      - name: active
        description: Indicates if the staff member is still working in the company
        tests:
          - accepted_values:
              values: [0,1]
              quote: false
      - name: store_id
        description: Foreign key referencing the 'stg_ae_local_bike__stores.store_id' column
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_ae_local_bike__stores
              to: ref('stg_ae_local_bike__stores')
              field: store_id
      - name: manager_id
        description: unique identifier of the staff member's manager

  - name: stg_ae_local_bike__stocks
    description: This model gives a current snapshot of the number of product items in each store
    columns:
      - name: stocks_id
        description: Primary key, unique identifier for the stocks, generated by combining the store_id and the product_id
        tests:
          - unique
          - not_null
      - name: store_id
        description: Foreign key referencing the 'stg_ae_local_bike__stores.store_id' column
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_ae_local_bike__stores
              to: ref('stg_ae_local_bike_stores')
              field: store_id
      - name: product_id
        description: Foreign key referencing the 'stg_ae_local_bike__products.product_id' column
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_ae_local_bike__products
              to: ref('stg_ae_local_bike__products')
              field: product_id

  - name: stg_ae_local_bike__stores
    description: This model maps the store id to the store name, contacts and address
    columns:
      - name: store_id
        description: Primary key, unique identifier of the store
        tests:
          - unique
          - not_null